### ISSUE TITLE
Advanced search like OL

### ISSUE THREAD

**Issue by escowles** [pulibrary/cicognara-rails#299]
Advanced search limits should be the same as the facets.

**Comment by jrgriffiniii** [comment]
I've integrated the `blacklight_range_limit` Gem in order to try and maintain feature parity with the advanced search on Orangelight:

<img width="1287" alt="cicognara-rails_issues-299-jrgriffiniii-advanced-search_screenshot_2" src="https://user-images.githubusercontent.com/1443986/53572760-ffa9bf00-3b39-11e9-8826-403087594b84.png">
<img width="1319" alt="cicognara-rails_issues-299-jrgriffiniii-advanced-search_screenshot_3" src="https://user-images.githubusercontent.com/1443986/53572767-02a4af80-3b3a-11e9-8c5f-0cfc27f026cf.png">
<img width="1292" alt="cicognara-rails_issues-299-jrgriffiniii-advanced-search_screenshot_4" src="https://user-images.githubusercontent.com/1443986/53572775-06d0cd00-3b3a-11e9-91aa-f4d788ccb104.png">

I've noticed that the fields used for the keyword search are distinct from the fields used for faceting (e. g. `subject` vs. `topic`).  Should these be treated as separate fields?  Faceting on `subject` for items such as https://cicognara-staging.princeton.edu/catalog/587 does not use an exposed facet, and refining the search by faceting upon the same value as a `topic` produces: https://cicognara-staging.princeton.edu/catalog?f%5Bsubject_facet%5D%5B%5D=Vitruvius+Pollio&f%5Bsubject_topic_facet%5D%5B%5D=Vitruvius+Pollio

**Comment by escowles** [comment]
@jrgriffiniii I think it makes sense to use the facet fields for the limits in the advanced search, and it looks like it works well.
