### ISSUE TITLE
Update Cicognara-Staging

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/cicognara-rails#337]

**Comment by jrgriffiniii** [comment]
Blocked by https://github.com/pulibrary/princeton_ansible/pull/456 and https://github.com/pulibrary/princeton_ansible/pulls

**Comment by jrgriffiniii** [comment]
I've tested and confirmed that invoking `cap [STAGE] deploy:reindex` does effectively regenerate reindex the TEI entries and MARC records into Solr.  It also rebuilds the partials.  Unfortunately, I've found that `nginx` in the server environment needs to be restarted *after* this is undertaken if one deploys and then reindexes (otherwise, Rails cannot find the newly-generated partials).

**Comment by jrgriffiniii** [comment]
Tracking the generated partials is one alternative I could propose given what I've encountered (please see https://github.com/pulibrary/cicognara-rails/commit/3d6222fda2178f2683a799fe212c8c15e47010df).

**Comment by escowles** [comment]
These are the kinds of problems I was thinking of when I created https://github.com/pulibrary/cicognara-rails/issues/236

Given the problems with static files, and the fact that very few of us can work effectively in XSLT, maybe we should rewrite those transforms in Ruby or otherwise completely change our approach.

**Comment by jrgriffiniii** [comment]
My only justification for tracking the partials would be that `cicognara-rails` already tracks the latest release of `cicognara-catalogo` in https://github.com/pulibrary/cicognara-rails/pull/263/files#diff-6dc906be0643182e5bae6aa1506221e6R33.  It also required less than 1 minute to redeploy (ensuring that it's more efficient than https://github.com/pulibrary/cicognara-rails/issues/317), but I completely understand why it's not a good practice to track these generated files.

**Comment by escowles** [comment]
If it doesn't make a big impact on deployment time and is more reliable than regenerating on deploy, I'd be fine with tracking the generated files for now, and leaving the decision about what to ultimately do about this to #236.

**Comment by jrgriffiniii** [comment]
This will be fully resolved once https://github.com/pulibrary/princeton_ansible/pull/456/files is merged, as provisioning to the staging server from the branch used for that pull request ensures that this app. can be deployed into the staging environment.
