### ISSUE TITLE
Sorting by date is not working

### ISSUE THREAD

**Issue by escowles** [pulibrary/cicognara-rails#439]
Reported by Holly: When I sort by date, items do not seem to be ordered by their dates. The first items don't display a date in the 1-line search results view. But even if you page past these items to ones that do show dates, they jump around instead of being in any kind of obvious order.

**Comment by hectorcorrea** [comment]
When sorting by date (e.g. "sort by year, newest first") the system is sorting based on the `pub_date_sort` field in Solr. The exact sort clause is [pub_date_sort desc, title_sort asc](https://github.com/pulibrary/cicognara-rails/blob/main/app/controllers/catalog_controller.rb#L210). 

The results displayed to the user come in the correct order based on the `pub_date_sort` value stored in Solr, however, what we display to the user sometimes shows either *no date* or a *different date* than the one stored in Solr.

For example, item [2591](https://cicognara.org/catalog/2591) has a `pub_date_sort` in Solr of 1821 but the TEI file for this item has a date of 1819 and we display the 1819 date to the user. You can view these values here: https://cicognara.org/catalog/2591.json, look for fields `tei_date_display` and `pub_date_sort`.

To a user this record should be displayed along other items from 1819 but instead if shows mixed with records from 1821 because the `pub_date_sort` has the 1821 value. See screenshot below.

![cicognara_dates](https://user-images.githubusercontent.com/568286/148289896-b598f393-1206-4b60-b489-3ae8f917f9c0.png)

Notice that when we display a record page (or a search result item) we are NOT using the data in Solr, instead we are using the pre-generated partials views under app/views/pages/catalogo. For example, for record 2591 we display the partial https://github.com/pulibrary/cicognara-rails/blob/main/app/views/pages/catalogo/_item_2591.html. Notice that this partial has the 1819 date.

We could probably re-generate the partials to include the `pub_date_sort` rather than the `tei_date_display` (or in addition to it?) but I am not sure of the ramifications of this.

**Comment by escowles** [comment]
Basically, it looks like the problem is that the display date and the data from the MARC records don't match. Maybe we should sort on `tei_date_display`, since that's pulled from the TEI like the displayed date?

**Comment by hectorcorrea** [comment]
The data in `tei_date_display' is a mess, sometimes it has values like ["A. 1541,"](https://cicognara.org/catalog/15.json) or ["1813 al 1818,"](https://cicognara.org/catalog/18.json) or [multiple values](https://cicognara.org/catalog/32.json). 

Plus it is stored but not indexed field.

**Comment by escowles** [comment]
@hectorcorrea OK, so it won't be as easy as that. But taking a look at the TEI, it does look like the overwhelming number of items have a four-digit year (or a range like `1813 al 1818`).  Could we update the indexer to parse the first 4-digit number into a new indexed field for sorting?

**Comment by hectorcorrea** [comment]
@escowles this has been deployed to staging (VPN required) https://cicognara-staging.princeton.edu/catalog?q=&search_field=all_fields&sort=pub_date_sort+desc%2C+title_sort+asc

Items come sorted properly by year of publication. 

There is one record (ID 3455) that does not display a year to the user but it is sorted correctly if you look at the raw data (https://cicognara-staging.princeton.edu/catalog/3455.json). The issue here is that there is no `tei_date_display` which is what it is used to generate the partials shown to the user, but we do have a date in MARC and the sort is honoring that. I think this is good enough but let me know what you think.

**Comment by escowles** [comment]
@hectorcorrea That is totally fine, thanks for getting this sorted out!
