### ISSUE TITLE
Evaluate Princeton data currently in Getty.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/cicognara-rails#454]
Make sure we don't have a bunch of bad data in Getty from us. If we do, add any failing test cases to https://github.com/pulibrary/figgy/issues/3904.

**Comment by lightgivener** [comment]
Hey Trey!

You mean PU holdings? Did you get anywhere with the off dcl identifiers Ani found in the PU records?

cheers

**Comment by tpendragon** [comment]
@lightgivener We're just getting started this week, so we haven't looked at any data cleanup yet.

**Comment by lightgivener** [comment]
ok! so the problem was that in the PU local holdings records - and only there - dcl numbers appear that I could find neither in the PU ShotList nor in any versions of the master file. They do have the typical dcl: abbreviation but are, to me, totally random three digit codes.

Please reach out to Ani Matosian as well if you need any examples or further info: amatosian@gmail.com.

Trying to send Princeton records to the portal might not make sense before these dcl codes are cleared up. Not sure how many there are. It is only a problem with physical PU book holdings related to Cicognara, not the fiche scans. Ani found at least a handful by happenstance.

Cheers!

**Comment by tpendragon** [comment]
Closing this as it was in regards to our OAI feed of data being sent to Getty, which is confirmed as being correct now. Closing.
