### ISSUE TITLE
Set title on catalog#show view

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/cicognara-rails#56]
Use from Entry if available, then try first MARC, then Catalogo Number

**Comment by jpstroop** [comment]
You'll need to add a title_s field to the TEIIndexer

**Comment by tampakis** [comment]
@cwulfman can you finish this issue? #68gives the TEIIndexer access to the MARC data (the marc titles are stored in the `title_t` field). In order to get a title to properly search and display, the `title_display` field must be set. Also, when a TEI title attribute is present it should be added to the `title_t` field, not `title_s`.
